### ISSUE TITLE
FootNet：an algorithm for the detection of foot strike and toe off events on non-instrumented treadmills

### ISSUE THREAD

**Issue by Allwillcome** [modenaxe/awesome-biomechanics#22]
[adrianrivadulla/FootNet](https://github.com/adrianrivadulla/FootNet)
Motion capture running analyses are often performed on conventional (non-instrumented) treadmills. The absence of force plates can be problematic for the detection of foot strike and toe off, which are critical for the comprehensive biomechanical analysis of running kinematics. We introduce FootNet an algorithm for the detection of foot strike and toe off events on non-instrumented treadmills using segment and joint kinematics as input. The algorithm is based on an LSTM neural network architecture that has been trained, validated and tested using five datasets collected in three independent motion capture labs.

**Comment by modenaxe** [comment]
Hi @Allwillcome, thank you for pointing this out.
@adrianrivadulla maybe you could be interested in helping me out here (based on previous conversations)?

**Comment by adrianrivadulla** [comment]
Hi Luca,

I hope everything went well in Ourense!

Sorry, I am quite new to some Github features and I am not sure what exactly I am being asked to do but yeah, sure happy to help! haha. Allwillcome had created an issue on our repo a few days ago and I replied and closed it. Is this post and your mention related to that one or is this new? His post is the beginning of the intro of our repo? I am not sure I follow. From your reply, it makes me think it may be about adding our repo to your awesome biomech repo? Is that what he's suggesting?

If that's the case, I am happy for our repo to be added to yours as we discussed last time, I'll confirm it with Ezio tomorrow just in case but i'm sure he'll be ok with it. I'll also check with our librarian about creating a doi for it as you mentioned last time.

Cheers,

Adrian

________________________________
De: Luca Modenese ***@***.***>
Enviado: luns, 20 de setembro de 2021 16:56
Para: modenaxe/awesome-biomechanics ***@***.***>
CC: Adrian Rodriguez Rivadulla ***@***.***>; Mention ***@***.***>
Asunto: Re: [modenaxe/awesome-biomechanics] FootNet：an algorithm for the detection of foot strike and toe off events on non-instrumented treadmills (#22)


CAUTION:  This email came from outside of the University. To keep your account safe, only click on links and open attachments if you know the person who sent the email, or you expected to receive this communication.



Hi @Allwillcome<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAllwillcome&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763715441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jJAmc21wqVa4kVgxsjr5QbfKFTAp%2F%2BUoosEM99nvszc%3D&reserved=0>, thank you for pointing this out.
@adrianrivadulla<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadrianrivadulla&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763725399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BPxBMD8s0gRLJtZQKOmYvascz7hyJod6odYEM8Fuvi8%3D&reserved=0> maybe you could be interested in helping me out here (based on previous conversations)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmodenaxe%2Fawesome-biomechanics%2Fissues%2F22%23issuecomment-923057132&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763725399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kqkR4o0ySG6zUo0EM%2Fu7Wz1nv92i7pXUQ20ZX%2FDSz4s%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIFQ7DAMFJGMHGMODSS6SDLUC5KR3ANCNFSM5DM54OUA&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763735343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WWzJDyS2YarmROqsmNyzXzUwYJglJtr5SUnLwY61M2w%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763735343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kLAGCajznYAL%2F49MmjvNPtoAPWKA6jFOQFJ5M4cT4O0%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763745297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oJw8QyxhIk2tSZT%2BXu718EgLtxWuztRtCnBMepeMg2A%3D&reserved=0>.

**Comment by Allwillcome** [comment]
> Hi Luca, I hope everything went well in Ourense! Sorry, I am quite new to some Github features and I am not sure what exactly I am being asked to do but yeah, sure happy to help! haha. Allwillcome had created an issue on our repo a few days ago and I replied and closed it. Is this post and your mention related to that one or is this new? His post is the beginning of the intro of our repo? I am not sure I follow. From your reply, it makes me think it may be about adding our repo to your awesome biomech repo? Is that what he's suggesting? If that's the case, I am happy for our repo to be added to yours as we discussed last time, I'll confirm it with Ezio tomorrow just in case but i'm sure he'll be ok with it. I'll also check with our librarian about creating a doi for it as you mentioned last time. Cheers, Adrian 嗨，卢卡，我希望在奥伦塞一切顺利！对不起，我对 Github 的一些特性还不太熟悉，我也不知道他们到底要我做什么，但是我很乐意帮忙！哈哈。几天前，allwilcome 在我们的回购协议上提出了一个问题，我回复了他，并且解决了这个问题。这篇文章和你提到的是和那篇文章有关还是这篇是新的？他的帖子是介绍我们回购的开始？我不太明白。从你的回复，它使我认为它可能是关于增加我们的回购到你了不起的生物技术回购？他是这个意思吗？如果是这样的话，我很高兴我们的回购协议能够像上次讨论的那样加入到你的协议中，我明天会和埃齐奥确认一下，以防万一，但是我相信他会接受的。我也会像你上次提到的那样，和我们的图书管理员一起为它创建一个 doi。干杯艾德里安
> […](#)
> ________________________________ De: Luca Modenese ***@***.***> Enviado: luns, 20 de setembro de 2021 16:56 Para: modenaxe/awesome-biomechanics ***@***.***> CC: Adrian Rodriguez Rivadulla ***@***.***>; Mention ***@***.***> Asunto: Re: [modenaxe/awesome-biomechanics] FootNet：an algorithm for the detection of foot strike and toe off events on non-instrumented treadmills ( 卢卡 · 摩登斯。Anviado: luns，2021年7月20日16:56第二段: modenaxe/awesome-生物力学。* * > CC: 阿德里安 · 罗德里格兹 · 瑞瓦杜拉。* * > ; 提到 * * * * * * * 。* * > Asunto: Re: [ modenaxe/awesome-biolics ] FootNet: 一种检测非仪器化跑步机上的足部撞击和脚趾脱落事件的算法([#22 22号](https://github.com/modenaxe/awesome-biomechanics/issues/22)) CAUTION: This email came from outside of the University. To keep your account safe, only click on links and open attachments if you know the person who sent the email, or you expected to receive this communication. Hi )警告: 这封邮件来自大学外部。为了保证你的账户安全，如果你认识发送邮件的人，或者你希望收到这封邮件，只点击链接并打开附件。嗨@Allwillcome @ 一切都会来<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAllwillcome&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763715441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jJAmc21wqVa4kVgxsjr5QbfKFTAp%2F%2BUoosEM99nvszc%3D&reserved=0>, thank you for pointing this out. 谢谢你指出这一点@adrianrivadulla @ adrianadulrivla<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadrianrivadulla&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763725399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BPxBMD8s0gRLJtZQKOmYvascz7hyJod6odYEM8Fuvi8%3D&reserved=0> maybe you could be interested in helping me out here (based on previous conversations)? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub< 也许你有兴趣帮帮我(根据以前的谈话) ？ー你收到这封信是因为有人提到你。直接回复此邮件，在 GitHub <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmodenaxe%2Fawesome-biomechanics%2Fissues%2F22%23issuecomment-923057132&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763725399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kqkR4o0ySG6zUo0EM%2Fu7Wz1nv92i7pXUQ20ZX%2FDSz4s%3D&reserved=0>, or unsubscribe< > ，或取消订阅https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIFQ7DAMFJGMHGMODSS6SDLUC5KR3ANCNFSM5DM54OUA&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763735343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WWzJDyS2YarmROqsmNyzXzUwYJglJtr5SUnLwY61M2w%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS< > . 在 iOS < 中使用 GitHub Mobile 分类通知https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763735343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kLAGCajznYAL%2F49MmjvNPtoAPWKA6jFOQFJ5M4cT4O0%3D&reserved=0> or Android< > 或 Android <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Carr43%40bath.ac.uk%7C9daa8579c543494792e108d97c4f2d1a%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C637677501763745297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oJw8QyxhIk2tSZT%2BXu718EgLtxWuztRtCnBMepeMg2A%3D&reserved=0>.

 I just think your work is worth letting more people see, and this warehouse provides this possibility😎.

**Comment by adrianrivadulla** [comment]
Thanks for that @Allwillcome, I will speak to my supervisors and Luca and we'll try to share it. I hope you didn't have any more issues when you tried our code. I am going to delete my previous response to Luca because it was meant to be a private email conversation. As I've mentioned in the message, I am quite new to some Github features.

**Comment by Allwillcome** [comment]
It‘s doesn't matter，Everyone will go through the novice process, and I am also exploring the features of GitHub.

**Comment by modenaxe** [comment]
resource added, thank you @adrianrivadulla and @Allwillcome !
